### ISSUE TITLE
Question on parameter glayerwise

### ISSUE THREAD

**Issue by lizhenstat** [jaehong-yoon93/CGES#4]
Hi, thanks for your work
I have one question on utils.py, what is the following parameter mean?
glayerwise = [1.,1.0, 1./15, 1./144]
elayerwise = [1.,0.5, 15., 144.]

Thanks in advance

**Comment by lizhenstat** [comment]
Hi, can you post the value of mu_l in cifar10 dataset? (what is the m there)
Thanks a lot

**Comment by lizhenstat** [comment]
@jaehong-yoon93

**Comment by jaehong31** [comment]
@lizhenstat Hi, Sorry for late check.
This is just because the conv params, and fc params show different distribution.
You can easily think that we use different hyperparameter to conv and fc for proper pruning.

**Comment by jaehong31** [comment]
@lizhenstat Thus, If you apply the model on other datasets, it depends on the condition of other parameters and sparsification level.

**Comment by lizhenstat** [comment]
@jaehong-yoon93 thanks for your replying.
However, I still cannot figure how you apply this equation get the above numbers(1, 15,144). Can you explain it in more detail? Is this pruning parameter different from the following equation in Section3.2
<a href="https://www.codecogs.com/eqnedit.php?latex=\mu&space;_{l}=m&plus;&space;(1-2m)\frac{l}{L-1}" target="_blank"><img src="https://latex.codecogs.com/gif.latex?\mu&space;_{l}=m&plus;&space;(1-2m)\frac{l}{L-1}" title="\mu _{l}=m+ (1-2m)\frac{l}{L-1}" /></a>
Thanks in advance

**Comment by jackliu333** [comment]
> @jaehong-yoon93 thanks for your replying.
> However, I still cannot figure how you apply this equation get the above numbers(1, 15,144). Can you explain it in more detail? Is this pruning parameter different from the following equation in Section3.2
> [![](https://camo.githubusercontent.com/6584762e5ad3ba7dd8fa93e8251713c6428b5274/68747470733a2f2f6c617465782e636f6465636f67732e636f6d2f6769662e6c617465783f5c6d752673706163653b5f7b6c7d3d6d2b2673706163653b28312d326d295c667261637b6c7d7b4c2d317d)](https://www.codecogs.com/eqnedit.php?latex=\mu&space;_{l}=m+&space;(1-2m)\frac{l}{L-1})
> Thanks in advance

Same here, not sure how it's applied in the code. Could you shed some light? @jaehong-yoon93

**Comment by jaehong-yoon93** [comment]
Well, in the given code, we balanced btw group and exclusive sparsity more drastically at higher fc layer; higher exclusive sparsification, lower group sparsification (which is consistent to our intuition). The values are not the results of sophisticated tuning. You can use other tuned values.

**Comment by jaehong31** [comment]
Well, in the code, we can say that this is a little bit of modified version (but still minor). We can easily understand that this just changes the scale of utilization btw two sparsifications drastically at higher fc layer than original version; much higher exclusive sparsification, and much lower group sparsification at higher fc layer(it is consistent to our intuition). 
Also, the exact values on that are not from sophisticated tuning, thus you can use any tuned parameters, do not worry about it. I think '0.5' in elayerwise has no specific meaning, that's okay to change '1' or something, actually I have no idea where it comes from.
